### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by Rhymond** [hcbt/checkprime#1]
Hey!
Thanks for the assessment, I have couple of comments:
* The application is not giving the correct response on the error input provided in the exercise.
Expected:
```
POST /
[1, 2, "nan"]

Response:
{
	error: "the given input is invalid. Element on index 3 is not a number"
}
```
Actual: "Invalid JSON payload"

* How we can automate API testing?
* Could you please explain the use of `sync.Map` in
https://github.com/hcbt/checkprime/blob/daf4ff21bfbeaee4ad51958614017937228ef25d/pkg/checkprime/checkprime.go#L6
* Could you explain how this code block is working? How can we test it? Can you spot any issues in it?
https://github.com/hcbt/checkprime/blob/daf4ff21bfbeaee4ad51958614017937228ef25d/internal/server/handlers/checkprimes.go#L35-L50
* What's the reason of this copy?
https://github.com/hcbt/checkprime/blob/daf4ff21bfbeaee4ad51958614017937228ef25d/internal/server/handlers/checkprimes.go#L52-L54
* What will happen if user provides a list of thousand huge numbers? How your API going to handle it? How we can test it?

**Comment by hcbt** [comment]
> Hey! Thanks for the assessment, I have couple of comments:
> 
> * The application is not giving the correct response on the error input provided in the exercise.
>   Expected:
> 
> ```
> POST /
> [1, 2, "nan"]
> 
> Response:
> {
> 	error: "the given input is invalid. Element on index 3 is not a number"
> }
> ```
> 
> Actual: "Invalid JSON payload"

Thanks for noticing this. Indeed it was giving an incorrect response. I have updated the code but will try to answer your comments where they still apply. 

> 
> * How we can automate API testing?

It depends. There is variety of tools and frameworks for that. You can use Postman, Jmeter, K6 and many others. Some of them probably do not integrate that well with CI/CD but k6 is a modern tool so it should be perfect for that.

> * Could you please explain the use of `sync.Map` in
>   
https://github.com/hcbt/checkprime/blob/daf4ff21bfbeaee4ad51958614017937228ef25d/pkg/checkprime/checkprime.go#L6

Sync.Map is thread-safe way to store and retrieve key-value pairs. I used it to implement a basic caching solution since I did not feel like setting up and using Redis for this simple task. It caches numbers that were already checked for being a prime number or not. While map would work as well, in my case I tried to use concurrency for each number inside a payload so Sync.Map was more suitable.

> * Could you explain how this code block is working? How can we test it? Can you spot any issues in it?
>   https://github.com/hcbt/checkprime/blob/daf4ff21bfbeaee4ad51958614017937228ef25d/internal/server/handlers/checkprimes.go#L35-L50

It performs validation on the req.Numbers slice to check if elements are valid integers. If the check fails - index of the invalid element is appended to the invalid slice. If any invalid elements are found, an error message is constructed and returned in the response along with a 400 Bad Request status code. The error message includes the indices of all invalid elements, joined together with a comma separator.

One potential issue with this code block is that it only checks for integer values and does not handle other types of input, such as floating-point numbers or strings. 

> * What will happen if user provides a list of thousand huge numbers? How your API going to handle it? How we can test it?

It depends. How big are the numbers actually? How many of them? In many libraries/frameworks standard timeout is usually around 30 seconds so if it takes longer than that to process those numbers you would just get timed-out. To avoid this, something like pagination could probably be implemented.
